
TEXT_FILE_NAME: str = "-TEXT_FILE_NAME-"
TEXT_CREATED_AT: str = "-TEXT_CREATED_AT-"
TEXT_DURATION: str = "-TEXT_DURATION-"
IN_FILE_INPUT: str = "-IN_FILE_INPUT-"
IN_TEXT_INPUT: str = "-IN_TEXT_INPUT-"
IN_FILE_NAME: str = "-IN_FILE_NAME-"
FILE_INFO_SECTION: str = "-FILE_INFO_SECTION-"
PLAYER_SECTION: str = "-PLAYER_SECTION-"
